### ISSUE TITLE
Objective-C unable to import Swift Packages

### ISSUE THREAD

**Issue by diogobalseiro** [trinhngocthuyen/cocoapods-spm#126]
### What happened?

Hello.
In my work to migrate a fairly large project from Cocoapods to SPM using the cocoapods-spm plugin, I've encountered an odd behaviour and would like to show it here.

## Context

There's this Swift package called [NetworkMonitor](https://github.com/Farfetch/network-monitor-ios), a fairly simple and vanilla framework for networking monitorization. It is 100% swift code, with some classes having @objc interop for convenience.

I've come to realize that I **cannot** import its module and use any of its @objc interop supporting classes from objective-c, when using the cocoapods-spm. I'm able to import the module when importing the package directly through the xcode's UI dependency picker.

I've setup a [sample repository](https://github.com/diogobalseiro/cocoapods-spm-interop-sample) which contains two projects, one that imports the package via Xcode, and another via cocoapods-spm.

Both projects are extremely simple, they contain a single swift file in the main target:

```
import FNMNetworkMonitor

public struct Something {

    let shared = FNMNetworkMonitor.shared
}

```

This file is correctly built in both projects. ✅

The projects also contain an objective-c .m file in the tests target:

```
#import <XCTest/XCTest.h>

@import FNMNetworkMonitor;

@interface interop_spmTests : XCTestCase

@end

@implementation interop_spmTests

- (void)testExample {

    FNMNetworkMonitor *shared = [FNMNetworkMonitor shared];

    XCTAssertNotNil(shared);
}

@end
```

This file builds and tests correctly in the xcode project that imports the FNMNetworkMonitor via xcode, but does not build and test when importing it via cocoapods-spm. ❌

I've tried other permutations, some not using a test target, but the result is always the same.

Any obvious reason for this?

The NetworkMonitor package is seemingly correct, as Xcode is able to handle it properly. Maybe some configuration is missing in the `Pods.xcodeproj` that gets generated? The NetworkMonitor contains no umbrella header file, or any objective-c code at all, simply the @objc interops.

Any feedback is appreciated. :pray:

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin21]
    RubyGems : 3.2.15
        Host : macOS 15.1 (24B83)
       Xcode : 16.1 (16B40)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/diogo.balseiro/.rbenv/versions/3.0.1/lib
Repositories :  trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/diogo.balseiro/.rbenv/versions/3.0.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-spm         : 0.1.6
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Sources configuration
source 'https://cdn.cocoapods.org/'

platform :ios
use_frameworks!

# Plugins

plugin 'cocoapods-spm'

# Pods used in multiple targets

target 'interop-plugin-spm' do

    pod 'interop-plugin-spm', :path => './'
    spm_pkg 'NetworkMonitor', :url => 'https://github.com/Farfetch/network-monitor-ios.git', :version => '12.1.0'
end
```

**Comment by trinhngocthuyen** [comment]
Hey there. Thank you for the detailed explanation. I'll take a look at this issue soon.

**Comment by trinhngocthuyen** [comment]
Hi @diogobalseiro, the issue should be fixed in #127.
Could you help check with the latest on main? Thank you

**Comment by diogobalseiro** [comment]
Hey @trinhngocthuyen 
Thanks for the quick turnaround 🙏 

Just tried using the plugin from branch `main` and the error persists in the sample project I linked in this issue's description. 🤔
Same error message as before.

**Comment by trinhngocthuyen** [comment]
I took a look at your sample project and there seems to be a misconfiguration.
- The test target `interop-plugin-spmTests` was not declared in the Podfile: https://github.com/diogobalseiro/cocoapods-spm-interop-sample/blob/278a14c/interop-plugin-spm/Podfile#L13-L17.
So, no pods or packages were handled for the test target.
- Also, the package `NetworkMonitor` was declared right under the app target only. So, the package is only visible to the main app. This behavior is the same as how pods behave.

I forked your sample project and made the demo changes in this commit. Kindly check it out:
https://github.com/trinhngocthuyen/cocoapods-spm-interop-sample/commit/fecb797afa9d88a4b75d9cb8e8dcb5b2eb0dfbdf

**Comment by trinhngocthuyen** [comment]
Thanks for letting me know about the compatibility with cocoapods 1.16.2 👍. I'll look into it.
Let's track that in a separate issue to keep this thread relevant.

**Comment by diogobalseiro** [comment]
Hey Chris

Regarding support for 1.16.X, should create a new issue?

**Comment by trinhngocthuyen** [comment]
Hey @diogobalseiro,
I'm using 1.16.2 for the integration project (see: [here](https://github.com/trinhngocthuyen/cocoapods-spm/blob/eca544e/Gemfile#L5)) and it works fine.

Could you help double-check on your end? If the issue persists, please help open a new issue with a reproducible sample project.
Thank you!

**Comment by diogobalseiro** [comment]
Hey @trinhngocthuyen 

Just after posting the comment, I went back and tried to reproduce the issue and couldn't! 🙃
I'm having trouble even remembering the exact problem I had before. Maybe the most recent version of Xcode/MacOS silently fixed whatever issue was happening, or maybe you made an unrelated change to the plugin.

All good then 👍
